### ISSUE TITLE
Methods `setParameters` and `getParameters` not included

### ISSUE THREAD

**Issue by mathysie** [mako-framework/docs#20]
The upgrading guide https://makoframework.com/docs/5.3/getting-started:upgrading#framework:http_middleware states that middleware parameters are set by `setParameters`. However, I cannot find a mention of `setParameters` nor an example at https://makoframework.com/docs/5.3/routing-and-controllers:routing#route_middleware.

Can you include the methods `setParameters` and `getParameters` in the documentation?

**Comment by freost** [comment]
Parameters are passed to `setParameters` automatically so you won't have to worry about that. There's an example with the `getParameters` method here https://makoframework.com/docs/5.3/routing-and-controllers:routing#route_middleware:defining_middleware

**Comment by mathysie** [comment]
While porting I got an error stating that `setParameters` is an abstract function so I needed to include a public function `setParameters` in my middleware. Is this intended?

**Comment by freost** [comment]
Yes but if you extend the `mako\http\routing\middleware\Middleware` abstract class then it's implemented for you (along with `getParameter`).

**Comment by mathysie** [comment]
OK, thanks!
